apps/departamentos/urls.py
from django.urls import path,include



from .views import DepartamentosList,DepartamentoCreate,DepartamentoUpdate,DepartamentoDelete

app_name = 'departamentos'


urlpatterns = [
    path('listar/',DepartamentosList.as_view(),name='list_departamentos'),
    path('novo',DepartamentoCreate.as_view(),name='create'),
    path('update/<int:pk>',DepartamentoUpdate.as_view(),name='update_departamento'),
    path('deletar/<int:pk>',DepartamentoDelete.as_view(),name='delete_departamento'),
   
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('empresa/', include('apps.empresa.urls')),
    path('registro_hora_extra/', include('apps.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/departamentos/models.py
from django.db import models
from django.urls  import reverse
from apps.empresa.models import Empresas
class Departamento(models.Model):
    nome = models.CharField(max_length=70)
    empresa = models.ForeignKey(Empresas,on_delete=models.PROTECT)


    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('departamentos:list_departamentos')
    

apps/departamentos/views.py
from django.shortcuts import render
from django.views.generic import ListView,UpdateView,DeleteView,CreateView
from django.urls import reverse_lazy

from .models import Departamento



class DepartamentosList(ListView):
    model = Departamento
    fields = ['nome']

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Departamento.objects.filter(empresa = empresa_logada)

class DepartamentoCreate(CreateView):
    model = Departamento
    fields = ['nome']

    def form_valid(self, form):
        departamento = form.save(commit=False)
        departamento.empresa = self.request.user.funcionario.empresa
        departamento.save()


        return super(DepartamentoCreate,self).form_valid(form)

class DepartamentoUpdate(UpdateView):
    model = Departamento
    fields = ['nome']

class DepartamentoDelete(DeleteView):
    model = Departamento
    success_url = reverse_lazy('departamentos:list_departamentos')

apps/departamentos/templates/departamentos/departamento_confirm_delete.html
{% extends 'base.html' %}


{% block main %}
<form action="" method="post">
 {% csrf_token %}
    <h1>Você quer excluir</h1>
    {{form}}

    <button type="submit" class="btn btn-danger">Cofirmar</button>

</form>
   
{% endblock  %}

apps/departamentos/templates/departamentos/departamento_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}

<form action="" method="post">

{% csrf_token %}

{{form|bootstrap}}

<button type="submit" class="btn btn-primary">Salvar</button>

</form>

{% endblock  %}

apps/departamentos/templates/departamentos/departamento_list.html
{% extends 'base.html' %}


{% block main %}
<a href="{% url 'departamentos:create' %}">Novo</a>
<table class="table">
    <thead>
        <tr>
            <td>#</td>
            <td>Nome</td>
            <td>Departamento</td>
        </tr>
    </thead>
    

    <tbody>
   
    {% for departamentos in object_list %}
    <tr>
            <td>{{departamentos.id}}</td>
            <td>{{departamentos.nome}}</td>
         
            <td>
              <a href="{% url 'departamentos:update_departamento' departamentos.id %}">Editar </a> 
             <a href="{% url 'departamentos:delete_departamento' departamentos.id %}">Deletar </a> 
         <br>
            </td>
    
    </tr>
    
     
    
    {% endfor %}
 </tbody>
</table>

      

{% endblock  %}