apps/documentos/urls.py
from django.urls import path,include
from .views import DocumentCreate


app_name = 'documentos'
urlpatterns = [
    
    path('novo/<int:funcionario_id>',DocumentCreate.as_view(),name='create_documento'),
    # path('novo',FuncionarioCreate.as_view(),name='create_funcionario'),
    # path('editar/<int:pk>',FuncionarioEdit.as_view(),name='update_funcionario'),
    # path('deletar/<int:pk>',FuncionarioDelete.as_view(),name='delete_funcionario'),
   
]

apps/funcionarios/urls.py
from django.urls import path,include
from .views import FuncionariosList,FuncionarioEdit,FuncionarioDelete,FuncionarioCreate


app_name = 'funcionarios'
urlpatterns = [
    
    path('',FuncionariosList.as_view(),name='list_funcionarios'),
    path('novo',FuncionarioCreate.as_view(),name='create_funcionario'),
    path('editar/<int:pk>',FuncionarioEdit.as_view(),name='update_funcionario'),
    path('deletar/<int:pk>',FuncionarioDelete.as_view(),name='delete_funcionario'),
   
]

apps/registro_hora_extra/urls.py
from django.urls import path, include
from .views import HoraExtraList, HoraExtraEdit, DeleteExtra, CreateHoraExtra


app_name = 'registro_hora_extra'
urlpatterns = [

    path('', HoraExtraList.as_view(), name='list_horaextra'),
    path('novo', CreateHoraExtra.as_view(), name='create_horaextra'),
    path('editar/<int:pk>', HoraExtraEdit.as_view(), name='edit_hora_extra'),
    path('delete/<int:pk>', DeleteExtra.as_view(), name='delete_hora_extra'),


]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('empresa/', include('apps.empresa.urls')),
    path('registro_hora_extra/', include('apps.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from apps.funcionarios.models import Funcionario
from django.urls import reverse
class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    user_id = models.ForeignKey(Funcionario,on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse("funcionarios:update_funcionario", args=[self.user_id.id])
    

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.departamentos.models import Departamento
from apps.empresa.models import Empresas
from django.urls import reverse
from django.db.models import Sum


class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT, default=1)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(
        Empresas, on_delete=models.PROTECT, default=0, null=True, blank=True)

    def get_absolute_url(self):
        return reverse("funcionarios:list_funcionarios")

    @property
    def total_horas_extra(self):
        total = self.registrohoraextra_set.all().aggregate(Sum('horas'))[
            'horas__sum']
        return total

    def __str__(self):
        return self.nome

apps/registro_hora_extra/models.py
from django.db import models
from apps.funcionarios.models import Funcionario
from django.urls import reverse


class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(
        Funcionario, on_delete=models.PROTECT, default=0)
    horas = models.DecimalField(max_digits=5, decimal_places=2)

    def get_absolute_url(self):
        return reverse("registro_hora_extra:edit_hora_extra", kwargs={"pk": self.id})

    def __str__(self):
        return self.motivo

apps/funcionarios/views.py
from urllib import request
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.views.generic import ListView,UpdateView,DeleteView,CreateView
from .models import Funcionario




class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa=empresa)


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome','departamentos']

class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('funcionarios:list_funcionarios')

class FuncionarioCreate(CreateView):
    model = Funcionario
    fields = ['nome','departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
       
       
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionarioSplit = funcionario.nome.split(' ')
        username = "{}{}".format(funcionarioSplit[0],funcionarioSplit[1])
        
      
        funcionario.user = User.objects.create(
             username= username
            
             )
        funcionario.save()
        return super(FuncionarioCreate,self).form_valid(form)



    

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}


{% block main %}
<form action="" method="post">
 {% csrf_token %}
    <h1>Você quer excluir</h1>
    {{form}}

    <button type="submit" class="btn btn-danger">Cofirmar</button>

</form>
   
{% endblock  %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}

<form action="" method="post">
{% csrf_token %}
{{form|bootstrap}}

<button type="submit" class="btn btn-success">Salvar</button>

</form>
<h2>Documentos</h2>

{% for documentos in object.documento_set.all %}
<ul class="list-group">
    <li class="list-group-item"><a href="{{ documentos.arquivo.url }}" target="_blank"> {{  documentos }}</a></li>
</ul>
  
{% endfor %}
<a href="{% url 'documentos:create_documento' object.id %}" class="btn btn-dark">Adicionar Documento</a>

<h2>Banco de Horas</h2>


{% for registro_hora in object.registrohoraextra_set.all %}
<ul class="list-group">
    <li class="list-group-item"><a href="{% url 'registro_hora_extra:edit_hora_extra' registro_hora.id %}"> {{  registro_hora }} | {{registro_hora.horas}}</a></li>
</ul>


  
{% endfor %}
<h3>Total Hora Extra {{ object.total_horas_extra }}</h3>
<a href="{% url 'registro_hora_extra:create_horaextra' %}" class="btn btn-dark">Adicionar Hora Extra</a>



{% endblock  %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}


{% block main %}
<a href="{% url 'funcionarios:create_funcionario' %}">Novo</a>
<table class="table">
    <thead>
        <tr>
            <td>#</td>
            <td>Nome</td>
            <td>Departamento</td>
        </tr>
    </thead>
    

    <tbody>
   
    {% for funcionario in object_list %}
    <tr>
            <td>{{funcionario.id}}</td>
            <td>{{funcionario.nome}}</td>
            <td>{{funcionario.departamentos}}</td>
            <td>
             <a href="{% url 'funcionarios:update_funcionario' funcionario.id %}">Editar </a>
             <a href="{% url 'funcionarios:delete_funcionario' funcionario.id %}">Deletar </a>
         <br>
            </td>
    
    </tr>
    
     
    
    {% endfor %}
 </tbody>
</table>

      

{% endblock  %}