apps/core/urls.py
from django.urls import path,include



from .views import home
app_name = 'core'
urlpatterns = [
    path('',home,name='home'),
   
]

apps/departamentos/urls.py
from django.urls import path,include



from .views import DepartamentosList,DepartamentoCreate,DepartamentoUpdate,DepartamentoDelete

app_name = 'departamentos'


urlpatterns = [
    path('listar/',DepartamentosList.as_view(),name='list_departamentos'),
    path('novo',DepartamentoCreate.as_view(),name='create'),
    path('update/<int:pk>',DepartamentoUpdate.as_view(),name='update_departamento'),
    path('deletar/<int:pk>',DepartamentoDelete.as_view(),name='delete_departamento'),
   
]

apps/empresa/urls.py
from django.urls import path,include



from .views import EmpresaCreate,EmpresaUpdate

app_name = 'empresa'


urlpatterns = [
    path('novo/',EmpresaCreate.as_view(),name='create'),
    path('editar/<int:pk>',EmpresaUpdate.as_view(),name='edit_empresa'),
   
]

apps/funcionarios/urls.py
from django.urls import path,include
from .views import FuncionariosList,FuncionarioEdit,FuncionarioDelete,FuncionarioCreate


app_name = 'funcionarios'
urlpatterns = [
    
    path('',FuncionariosList.as_view(),name='list_funcionarios'),
    path('novo',FuncionarioCreate.as_view(),name='create_funcionario'),
    path('editar/<int:pk>',FuncionarioEdit.as_view(),name='update_funcionario'),
    path('deletar/<int:pk>',FuncionarioDelete.as_view(),name='delete_funcionario'),
   
]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('empresa/', include('apps.empresa.urls')),
    path('registro_hora_extra/', include('apps.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <header>
            <!-- Fixed navbar -->
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
              <a class="navbar-brand" href="{% url 'core:home' %}">Django RH</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:home' %}">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'funcionarios:list_funcionarios'%}">Funcionarios</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'departamentos:list_departamentos'%}">Departamentos</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'registro_hora_extra:list_horaextra'%}"> Hora Extra</a>
                  </li>
                 
                  <li class="nav-item">
                    {% if usuario.funcionario.empresa %}
                        <a class="nav-link float-right" href="{% url 'empresa:edit_empresa' usuario.funcionario.empresa.id %}">Editar Empresa</a>
                    {% else %}
                        <a  class="nav-link float-right" href="{% url 'empresa:create' %}">Criar Empresa</a>
                    {% endif %}
                   
                  </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                  <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
              </div>
            </nav>
          </header>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div class="container">
            {% block main %}{% endblock  %}
        </div>
        
    </body>
</html>