apps/core/urls.py
from django.urls import path,include



from .views import home
app_name = 'core'
urlpatterns = [
    path('',home,name='home'),
   
]

apps/departamentos/urls.py
from django.urls import path,include



from .views import DepartamentosList,DepartamentoCreate,DepartamentoUpdate,DepartamentoDelete

app_name = 'departamentos'


urlpatterns = [
    path('listar/',DepartamentosList.as_view(),name='list_departamentos'),
    path('novo',DepartamentoCreate.as_view(),name='create'),
    path('update/<int:pk>',DepartamentoUpdate.as_view(),name='update_departamento'),
    path('deletar/<int:pk>',DepartamentoDelete.as_view(),name='delete_departamento'),
   
]

apps/empresa/urls.py
from django.urls import path,include



from .views import EmpresaCreate,EmpresaUpdate

app_name = 'empresa'


urlpatterns = [
    path('novo/',EmpresaCreate.as_view(),name='create'),
    path('editar/<int:pk>',EmpresaUpdate.as_view(),name='edit_empresa'),
   
]

apps/funcionarios/urls.py
from django.urls import path,include
from .views import FuncionariosList,FuncionarioEdit,FuncionarioDelete,FuncionarioCreate


app_name = 'funcionarios'
urlpatterns = [
    
    path('',FuncionariosList.as_view(),name='list_funcionarios'),
    path('novo',FuncionarioCreate.as_view(),name='create_funcionario'),
    path('editar/<int:pk>',FuncionarioEdit.as_view(),name='update_funcionario'),
    path('deletar/<int:pk>',FuncionarioDelete.as_view(),name='delete_funcionario'),
   
]

apps/registro_hora_extra/urls.py
from django.urls import path, include
from .views import HoraExtraList, HoraExtraEdit, DeleteExtra, CreateHoraExtra


app_name = 'registro_hora_extra'
urlpatterns = [

    path('', HoraExtraList.as_view(), name='list_horaextra'),
    path('novo', CreateHoraExtra.as_view(), name='create_horaextra'),
    path('editar/<int:pk>', HoraExtraEdit.as_view(), name='edit_hora_extra'),
    path('delete/<int:pk>', DeleteExtra.as_view(), name='delete_hora_extra'),


]

gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('empresa/', include('apps.empresa.urls')),
    path('registro_hora_extra/', include('apps.registro_hora_extra.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

# Create your models here.

apps/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from apps.funcionarios.models import Funcionario


@login_required
def home(request):
    data = {}
    data['usuario'] = request.user
    return render(request,'core/index.html',data)

apps/core/templates/core/index.html
{% extends 'base.html' %}


{% block main %}

<div class="row">
    <div class="col-sm"></div>
    <div class="col-sm">Olá {{usuario.funcionario.nome}} 
    
        <a href="{% url 'funcionarios:list_funcionarios'%}">Listar Funcionarios</a>
        <a href="{% url 'departamentos:list_departamentos'%}">Listar Departamentos</a>
        <a href="{% url 'registro_hora_extra:list_horaextra'%}">Listar Hora Extra</a>
     </div>
    <div class="col-sm">
        <a href="{% url 'logout' %}">Sair</a>

        {% if usuario.funcionario.empresa %}
            <a href="{% url 'empresa:edit_empresa' usuario.funcionario.empresa.id %}">Editar Empresa</a>
        {% else %}
            <a href="{% url 'empresa:create' %}">Criar Empresa</a>
        {% endif %}
    
     </div>

</div>

{% endblock %}